### ISSUE TITLE
Mirror to GitLab

### ISSUE THREAD

**Issue by kathryn-garside** [NewcastleRSE/xray-spectroscopy-ml#57]
GitHub Actions Marketplace has an action to allow mirroring of a GitHub repo onto GitLab:

https://github.com/marketplace/actions/mirror-to-gitlab-and-run-gitlab-ci

As long as the main branch always remains functional then the action could be triggered on a merge to main. For example,

```
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
```

Or when some other release condition is met.
